version: '3.9'

networks:
  pagarme.network:
    driver: bridge

services:
  webserver:
    build: ./docker
    container_name: pagarme.php
    tty: true
    volumes:
      - ./:/app
    networks:
      - pagarme.network
    ports:
      - "80:80"
      - "443:443"